<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <PackageId>Kkhay</PackageId>
    <Version>1.0.0</Version>
    <Authors>K Khay</Authors>
    <Company>K Khay</Company>
    <Description>Official C# and .NET SDK for K Khay Sovereign Crypto Payment Gateway</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://kkhay.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/boboaungdev/kkhay-dotnet</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>crypto;payments;gateway;web3;usdt;bitcoin;blockchain</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

</Project>
